Invite
hicsail/anchor pull request #136
Opened 2018-07-13 17:46 UTC by FrancisZamora

invite model

2018-07-13 19:15 UTC, gregfrasco requested changes

2018-07-13 19:15 UTC, gregfrasco commented on server/models/invite.js
> +  static async create(email,status) {
update this to be a JSON object called document so it will work with anchor API

2018-07-13 19:15 UTC, gregfrasco commented on server/models/invite.js
> +      createdAt: new Date(),
remove Allow Anchor Model to create it

2018-07-16 23:26 UTC, FrancisZamora commented
I removed the createdAt and updatedAt from the create method and the schema, will the anchor model still be able to generate a timestamp?

2018-07-17 12:13 UTC, gregfrasco approved these changes

2018-07-17 12:13 UTC, merged