Permissions
hicsail/anchor pull request #171
Opened 2018-08-03 18:13 UTC by esenharris4

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-08-03 19:17 UTC, esenharris4 commented
Completed the user and role permissions routes. Now we just have to create a system to send the json through

2018-08-06 16:40 UTC, gregfrasco requested changes

2018-08-06 16:40 UTC, gregfrasco commented on server/api/permissions.js
> +      return await Role.updateRole(objectid,permissions,name);
Don't need to write a function within the roles model. Just call `await Role.findbyIdandUpdate(id, {$set {...}})`

2018-08-06 16:40 UTC, gregfrasco commented on server/api/permissions.js
> +      return await User.updateUserPermissions(objectid,permissions);
Remove function, just update the user in this function

2018-08-06 19:21 UTC, gregfrasco approved these changes

2018-08-06 19:21 UTC, gregfrasco commented on server/models/role.js
> +
remove

2018-08-06 19:21 UTC, gregfrasco commented on server/models/user.js
> +const ObjectId = require('mongodb').ObjectID;
remove

2018-08-06 19:21 UTC, gregfrasco commented on server/models/role.js
> +const ObjectId = require('mongodb').ObjectID;
remove

2018-08-06 19:55 UTC, merged